/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "uycwlrqdboftyjrtpqsq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Y3dscnFkYm9mdHlqcnRwcXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MjM1MzYsImV4cCI6MjA3NzI5OTUzNn0.qfEhLDux_O5Dx2yKd-FI4iRE-AUtesm8JhyporP1yrU"